COLOR_DEPTH: str = "COLOR_DEPTH"
DEFAULT_COLOR_DEPTH: int = 4

AMOUNT_OF_PARTICLES: str = "AMOUNT_OF_PARTICLES"
DEFAULT_AMOUNT_OF_PARTICLES: int = 1500

TURN_ON_MUSIC: bool = False
BEAT_UPDATE_SECOND: float = 0.1
